import type{CharacterConfig,Relationship}from'../types';
export const characters:CharacterConfig[]=[
 {id:'arianna',name:'Arianna',shortName:'ARI',appearance:{skin:'#d8a07d',hair:'#36251f',shirt:'#765df0',accent:'#65b9ff',height:42,hairStyle:'long',headphones:true},speed:22,preferred:['WALK','DRINK','TALK'],phrases:['Mi scappa la pipì','Delivery mode!'],signature:'cuffie + borraccia'},
 {id:'stucchi',name:'Daniele Stucchi',shortName:'STU',appearance:{skin:'#d6a17a',hair:'#51382b',shirt:'#384b68',accent:'#3487da',height:43,hairStyle:'sparse',glasses:true,beard:true},speed:25,preferred:['WORK','SMOKE','CHASE'],phrases:['@#!%','Quel player...'],signature:'CTV + rincorsa'},
 {id:'pulici',name:'Daniele Pulici',shortName:'PUL',appearance:{skin:'#d8a27a',hair:'#6a4932',shirt:'#314b70',accent:'#89a7cd',height:44,hairStyle:'short',beard:true},speed:50,preferred:['RUN','PHONE','WORK'],phrases:['Dopo ci sentiamo.'],signature:'sempre di corsa'},
 {id:'andrea',name:'Andrea',shortName:'AND',appearance:{skin:'#d49a74',hair:'#282426',shirt:'#657446',accent:'#b6cb64',height:40,hairStyle:'curly'},speed:21,preferred:['WALK','SMOKE','TALK'],phrases:['Jafer...','Ma fammi fini—'],signature:'musica + discussioni'},
 {id:'jafer',name:'Jafer',shortName:'JAF',appearance:{skin:'#a86f50',hair:'#171719',shirt:'#c75e45',accent:'#f2a66f',height:44,hairStyle:'short'},speed:24,preferred:['TALK','WALK','TALK'],phrases:['No perché—','ASPETTA'],signature:'social continuo'},
 {id:'priscilla',name:'Priscilla',shortName:'PRI',appearance:{skin:'#e0ad88',hair:'#d6aa56',shirt:'#d86b9c',accent:'#ffe7a7',height:43,hairStyle:'long',glasses:true},speed:22,preferred:['TALK','IDLE','WALK'],phrases:['Ahahah!'],signature:'risata sociale'},
 {id:'umberto',name:'Umberto',shortName:'UMB',appearance:{skin:'#d5a07d',hair:'#69452f',shirt:'#e8edf4',accent:'#4f6e91',height:45,hairStyle:'short',beard:true},speed:20,preferred:['TALK','IDLE','WORK'],phrases:['AHAHAHA!'],signature:'risata sismica'},
 {id:'luca',name:'Luca',shortName:'LUC',appearance:{skin:'#d29b74',hair:'#67452f',shirt:'#586f8e',accent:'#b4c8df',height:46,hairStyle:'long',beard:true},speed:20,preferred:['TALK','WORK','IDLE'],phrases:['...come si dice?'],signature:'parole in costruzione'},
 {id:'emanuele',name:'Emanuele',shortName:'EMA',appearance:{skin:'#d39d76',hair:'#67452f',shirt:'#3d856e',accent:'#78d0a8',height:44,hairStyle:'short'},speed:23,preferred:['TALK','SMOKE','WALK'],phrases:['Ne ho una...'],signature:'battute'},
 {id:'john',name:'John',shortName:'JHN',appearance:{skin:'#a56e51',hair:'#19191b',shirt:'#456996',accent:'#8db4e2',height:53,hairStyle:'short',glasses:true},speed:30,preferred:['WORK','WORK','CHASE'],phrases:['Robot mode'],signature:'work + inseguimenti'},
 {id:'fabio',name:'Fabio',shortName:'FAB',appearance:{skin:'#d39b76',hair:'#44322a',shirt:'#5b61ed',accent:'#73d8cf',height:45,hairStyle:'short'},speed:26,preferred:['MUSIC','WORK','WALK'],phrases:['Debug... fix ✓','+1 tool installed'],signature:'builder + musica'}
];
export const relationships:Relationship[]=[
 {from:'arianna',to:'fabio',kind:'HIGH',weight:1},{from:'fabio',to:'arianna',kind:'HIGH',weight:1},{from:'arianna',to:'priscilla',kind:'HIGH',weight:1},{from:'priscilla',to:'arianna',kind:'HIGH',weight:1},{from:'arianna',to:'jafer',kind:'SOCIAL',weight:.7},{from:'priscilla',to:'jafer',kind:'HIGH',weight:1},{from:'jafer',to:'priscilla',kind:'HIGH',weight:1},{from:'andrea',to:'jafer',kind:'CHAOTIC',weight:1},{from:'jafer',to:'andrea',kind:'CHAOTIC',weight:1},{from:'umberto',to:'emanuele',kind:'HIGH',weight:1},{from:'emanuele',to:'umberto',kind:'HIGH',weight:1},{from:'emanuele',to:'jafer',kind:'HIGH',weight:.9},{from:'jafer',to:'emanuele',kind:'HIGH',weight:.9},{from:'stucchi',to:'john',kind:'CHASE',weight:1},{from:'john',to:'fabio',kind:'CHASE',weight:1}
];
export const byId=Object.fromEntries(characters.map(c=>[c.id,c])) as Record<CharacterConfig['id'],CharacterConfig>;
