import{byId,characters,relationships}from'../config/characters';
import type{Actor,Bounds,CharacterId,CharacterState}from'../types';
export const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));
export const distance=(a:Actor,b:Actor)=>Math.hypot(a.x-b.x,a.y-b.y);
const pick=<T,>(xs:T[],random=Math.random)=>xs[Math.floor(random()*xs.length)];
export function initialActors(bounds:Bounds):Actor[]{const floor=Math.min(300,Math.max(100,bounds.height-150));return characters.map((c,i)=>({id:c.id,x:45+(i%6)*Math.max(90,(bounds.width-100)/6),y:floor+Math.floor(i/6)*72,tx:80+((i*137)%Math.max(100,bounds.width-160)),ty:floor+((i*43)%Math.max(50,bounds.height-floor-60)),state:'IDLE',facing:1,until:0,lastEvent:0,clicks:0}))}
export function validTransition(from:CharacterState,to:CharacterState){if(from==='SPECIAL')return to==='IDLE';if(from==='SLEEP')return to==='IDLE'||to==='WALK';return true}
export function newTarget(bounds:Bounds,random=Math.random){const floor=bounds.height>400?300:65;return{x:50+random()*Math.max(20,bounds.width-100),y:floor+random()*Math.max(20,bounds.height-floor-55)}}
export function stepActors(actors:Actor[],bounds:Bounds,now:number,dt:number,random=Math.random,reduced=false):Actor[]{const next=actors.map(a=>({...a}));if(reduced)return next.map(a=>({...a,state:'IDLE',bubble:a.bubbleUntil&&a.bubbleUntil>now?a.bubble:undefined}));for(const a of next){const cfg=byId[a.id];if(a.bubbleUntil&&a.bubbleUntil<now)a.bubble=undefined;if(now>a.until){const target=newTarget(bounds,random);a.tx=target.x;a.ty=target.y;a.state=pick(cfg.preferred,random);a.until=now+1800+random()*3200;if(['IDLE','WORK','PHONE','SMOKE','DRINK','MUSIC','TALK'].includes(a.state)){a.tx=a.x;a.ty=a.y}}const relation=relationships.find(r=>r.from===a.id&&r.kind==='CHASE');if(relation){const target=next.find(x=>x.id===relation.to);if(target&&distance(a,target)<190&&random()<.025){a.state='CHASE';a.tx=target.x;a.ty=target.y;a.until=now+1800}}if(a.id==='pulici'){if(a.state==='IDLE'&&random()<.85)a.state='RUN';if(random()<.006){a.state='PHONE';a.bubble='Dopo ci sentiamo.';a.bubbleUntil=now+1900;a.until=now+1300}}const speed=(a.state==='RUN'||a.state==='CHASE'?cfg.speed*1.75:cfg.speed)*dt,dx=a.tx-a.x,dy=a.ty-a.y,len=Math.hypot(dx,dy);if(len>3){a.x=clamp(a.x+dx/len*speed,28,bounds.width-28);a.y=clamp(a.y+dy/len*speed,48,bounds.height-48);a.facing=dx<0?-1:1}else if(['WALK','RUN','CHASE'].includes(a.state)){const t=newTarget(bounds,random);a.tx=t.x;a.ty=t.y}}return next}
export function socialEvent(actors:Actor[],now:number,random=Math.random){const active=actors.filter(a=>a.bubble&&a.bubbleUntil!>now).length;if(active>=2)return{actors,event:null};const out=actors.map(a=>({...a})),andrea=out.find(a=>a.id==='andrea')!,jafer=out.find(a=>a.id==='jafer')!;if(distance(andrea,jafer)<155&&now-andrea.lastEvent>9000&&random()<.32){andrea.bubble='Ma fammi fini—';jafer.bubble='ASPETTA';andrea.bubbleUntil=jafer.bubbleUntil=now+2300;andrea.lastEvent=jafer.lastEvent=now;andrea.state=jafer.state='TALK';return{actors:out,event:'argument'}}const ema=out.find(a=>a.id==='emanuele')!,umb=out.find(a=>a.id==='umberto')!;if(distance(ema,umb)<150&&now-umb.lastEvent>12000&&random()<.18){ema.bubble='Ne ho una...';umb.bubble='AHAHAHA!';ema.bubbleUntil=umb.bubbleUntil=now+2100;ema.lastEvent=umb.lastEvent=now;return{actors:out,event:'umberto-laugh'}}const eligible=out.filter(a=>now-a.lastEvent>8000);if(eligible.length&&random()<.08){const a=pick(eligible,random),cfg=byId[a.id];a.bubble=pick(cfg.phrases,random);a.bubbleUntil=now+1900;a.lastEvent=now;return{actors:out,event:a.id==='fabio'?'builder':'speech'}}return{actors:out,event:null}}
export function puliciAvoids(pulici:Actor,other:Actor){return pulici.id==='pulici'&&distance(pulici,other)<120}
export function chaseTarget(id:CharacterId){return relationships.find(r=>r.from===id&&r.kind==='CHASE')?.to??null}
