import {useEffect,useState} from 'react';
import {Download,ExternalLink,LogOut,Play,RefreshCw,Search,ShieldCheck,Wrench} from 'lucide-react';
import {api} from './api';
import {check} from '@tauri-apps/plugin-updater';
import type {Catalog,DeviceCode,Tool} from './types';
import {LabAlive} from './features/lab-alive/LabAlive';

function friendly(e:unknown){return String(e).replace(/^Error:\s*/, '')}
export default function App(){
 const [auth,setAuth]=useState<boolean|null>(null),[code,setCode]=useState<DeviceCode|null>(null),[catalog,setCatalog]=useState<Catalog|null>(null);
 const [busy,setBusy]=useState<string|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[updateText,setUpdateText]=useState('');
 useEffect(()=>{api.session().then(setAuth).catch(e=>{setError(friendly(e));setAuth(false)});void autoUpdate()},[]);
 useEffect(()=>{if(auth) refresh()},[auth]);
 async function refresh(){setBusy('catalog');setError('');try{setCatalog(await api.catalog())}catch(e){setError(friendly(e))}finally{setBusy(null)}}
 async function login(){setError('');try{const c=await api.beginLogin();setCode(c);await api.openUrl(c.verification_uri);setBusy('login');await api.finishLogin(c);setAuth(true);setCode(null)}catch(e){setError(friendly(e))}finally{setBusy(null)}}
 async function act(tool:Tool,kind:'install'|'open'){setBusy(tool.repo);setError('');try{await api[kind](tool);if(kind==='install')await refresh()}catch(e){setError(friendly(e))}finally{setBusy(null)}}
 async function logout(){await api.logout();setAuth(false);setCatalog(null)}
 async function autoUpdate(){try{const update=await check({timeout:15000});if(!update)return;setUpdateText(`Aggiornamento ${update.version} in download…`);let downloaded=0,total=0;await update.downloadAndInstall(e=>{if(e.event==='Started')total=e.data.contentLength??0;if(e.event==='Progress'){downloaded+=e.data.chunkLength;setUpdateText(total?`Aggiornamento ${update.version}: ${Math.round(downloaded/total*100)}%`:`Aggiornamento ${update.version}…`)}if(e.event==='Finished')setUpdateText('Installazione aggiornamento…')})}catch(e){console.warn('Updater:',e)}}
 if(auth===null)return <main className="center"><div className="spinner"/></main>;
 if(!auth)return <main className="login"><section className="loginCard"><div className="logo"><Wrench size={28}/></div><h1>QA Lab Launcher</h1><p>I tuoi strumenti QA, sempre aggiornati e pronti all'uso.</p>{code&&<div className="device"><small>Inserisci questo codice su GitHub</small><strong>{code.user_code}</strong><button className="link" onClick={()=>api.openUrl(code.verification_uri)}>Apri GitHub <ExternalLink size={15}/></button></div>}<button className="primary" disabled={busy==='login'} onClick={login}>{busy==='login'?<><span className="miniSpinner"/> In attesa di GitHub…</>:<>Accedi con GitHub</>}</button>{error&&<div className="error">{error}</div>}<div className="secure"><ShieldCheck size={15}/> Accesso protetto tramite GitHub Device Flow</div></section></main>;
 const shown=(catalog?.tools??[]).filter(t=>(t.name+' '+t.description+' '+t.repo).toLowerCase().includes(query.toLowerCase()));
 return <main><header><div className="brand"><div className="logo small"><Wrench size={20}/></div><div><b>QA Lab</b><span>Launcher</span></div></div><div className="headActions">{updateText&&<span className="updateText"><span className="miniSpinner"/>{updateText}</span>}<button className="iconBtn" title="Aggiorna" onClick={refresh}><RefreshCw size={18} className={busy==='catalog'?'spin':''}/></button><button className="logout" onClick={logout}><LogOut size={17}/> Esci</button></div></header><div className="content"><div className="title"><div><h1>I tuoi strumenti</h1><p>{catalog?`${catalog.tools.length} strumenti disponibili${catalog.unconfigured?` · ${catalog.unconfigured} repository non configurate`:''}`:'Caricamento catalogo…'}</p></div><label className="search"><Search size={18}/><input placeholder="Cerca strumenti…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>{error&&<div className="error wide">{error}</div>}{busy==='catalog'&&!catalog?<div className="empty"><div className="spinner"/><p>Controllo repository e release…</p></div>:shown.length?<div className="grid">{shown.map(t=><ToolCard key={`${t.owner}/${t.repo}`} tool={t} busy={busy===t.repo} act={act}/>)}</div>:<div className="empty"><Wrench size={40}/><h2>Nessuno strumento disponibile</h2><p>Le repository devono contenere un launcher.json valido e una release Windows.</p></div>}{catalog?.warnings.length?<details><summary>Avvisi ({catalog.warnings.length})</summary>{catalog.warnings.map((w,i)=><p key={i}>{w}</p>)}</details>:null}<LabAlive/></div></main>
}
function ToolCard({tool,busy,act}:{tool:Tool,busy:boolean,act:(t:Tool,k:'install'|'open')=>void}){const update=tool.status==='update_available',installed=tool.status!=='not_installed';return <article className="card"><div className="toolIcon">{tool.icon_url?<img src={tool.icon_url}/>:tool.name.slice(0,2).toUpperCase()}</div><div className="toolText"><div className="cardTop"><h2>{tool.name}</h2><span className={`badge ${tool.status}`}>{tool.status==='updated'?'Aggiornato':update?'Aggiornamento':'Non installato'}</span></div><p>{tool.description||'Nessuna descrizione disponibile.'}</p><div className="meta"><span>v{tool.remote_version}</span><span>{tool.owner}/{tool.repo}</span></div></div><button className={installed&&!update?'open':'primary compact'} disabled={busy} onClick={()=>act(tool,installed&&!update?'open':'install')}>{busy?<span className="miniSpinner"/>:installed&&!update?<><Play size={16}/> Apri</>:<><Download size={16}/> {update?'Aggiorna':'Installa'}</>}</button></article>}
